/*
 * Galaxy Training Network API
 *
 * A collection of tutorials generated and maintained by Galaxy Community Members across the world
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct User {
    /// The user ID, usually their GitHub username
    #[serde(rename = "id")]
    pub id: String,
    /// The name they wish to be refered to with.
    #[serde(rename = "name")]
    pub name: String,
    /// Their email
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// ORCID ID
    #[serde(rename = "orcid", skip_serializing_if = "Option::is_none")]
    pub orcid: Option<String>,
    /// Twitter Handle
    #[serde(rename = "twitter", skip_serializing_if = "Option::is_none")]
    pub twitter: Option<String>,
    /// Linkedin Handle
    #[serde(rename = "linkedin", skip_serializing_if = "Option::is_none")]
    pub linkedin: Option<String>,
    /// If their username is not equivalent to their github name
    #[serde(rename = "github", skip_serializing_if = "Option::is_none")]
    pub github: Option<bool>,
    /// Their preferred contact method
    #[serde(rename = "maintainer_contact", skip_serializing_if = "Option::is_none")]
    pub maintainer_contact: Option<String>,
    /// Year + Month (0 padded) when they joined the GTN
    #[serde(rename = "joined")]
    pub joined: String,
}

impl User {
    pub fn new(id: String, name: String, joined: String) -> User {
        User {
            id,
            name,
            email: None,
            orcid: None,
            twitter: None,
            linkedin: None,
            github: None,
            maintainer_contact: None,
            joined,
        }
    }
}


